config/routes.rb
Rails.application.routes.draw do
  resources :contact_forms
  resources :product_discount_packages
  resources :products
  resources :product_types
  get 'main/home'
  get 'main/contact'
  root 'main#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product_discount_package.rb
class ProductDiscountPackage < ApplicationRecord
end

app/controllers/product_discount_packages_controller.rb
class ProductDiscountPackagesController < ApplicationController
  before_action :set_product_discount_package, only: %i[ show edit update destroy ]

  # GET /product_discount_packages or /product_discount_packages.json
  def index
    @product_discount_packages = ProductDiscountPackage.all
  end

  # GET /product_discount_packages/1 or /product_discount_packages/1.json
  def show
  end

  # GET /product_discount_packages/new
  def new
    @product_discount_package = ProductDiscountPackage.new
  end

  # GET /product_discount_packages/1/edit
  def edit
  end

  # POST /product_discount_packages or /product_discount_packages.json
  def create
    @product_discount_package = ProductDiscountPackage.new(product_discount_package_params)

    respond_to do |format|
      if @product_discount_package.save
        format.html { redirect_to @product_discount_package, notice: "Product discount package was successfully created." }
        format.json { render :show, status: :created, location: @product_discount_package }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_discount_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_discount_packages/1 or /product_discount_packages/1.json
  def update
    respond_to do |format|
      if @product_discount_package.update(product_discount_package_params)
        format.html { redirect_to @product_discount_package, notice: "Product discount package was successfully updated." }
        format.json { render :show, status: :ok, location: @product_discount_package }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_discount_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_discount_packages/1 or /product_discount_packages/1.json
  def destroy
    @product_discount_package.destroy
    respond_to do |format|
      format.html { redirect_to product_discount_packages_url, notice: "Product discount package was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_discount_package
      @product_discount_package = ProductDiscountPackage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_discount_package_params
      params.require(:product_discount_package).permit(:name, :description, :discount_percentage)
    end
end

app/helpers/product_discount_packages_helper.rb
module ProductDiscountPackagesHelper
end

app/views/product_discount_packages/_form.html.erb
<%= form_with(model: product_discount_package) do |form| %>
  <% if product_discount_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_discount_package.errors.count, "error") %> prohibited this product_discount_package from being saved:</h2>

      <ul>
        <% product_discount_package.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :discount_percentage %>
    <%= form.text_field :discount_percentage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_discount_packages/edit.html.erb
<h1>Editing Product Discount Package</h1>

<%= render 'form', product_discount_package: @product_discount_package %>

<%= link_to 'Show', @product_discount_package %> |
<%= link_to 'Back', product_discount_packages_path %>

app/views/product_discount_packages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Discount Packages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Discount percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_discount_packages.each do |product_discount_package| %>
      <tr>
        <td><%= product_discount_package.name %></td>
        <td><%= product_discount_package.description %></td>
        <td><%= product_discount_package.discount_percentage %></td>
        <td><%= link_to 'Show', product_discount_package %></td>
        <td><%= link_to 'Edit', edit_product_discount_package_path(product_discount_package) %></td>
        <td><%= link_to 'Destroy', product_discount_package, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Discount Package', new_product_discount_package_path %>

app/views/product_discount_packages/new.html.erb
<h1>New Product Discount Package</h1>

<%= render 'form', product_discount_package: @product_discount_package %>

<%= link_to 'Back', product_discount_packages_path %>

app/views/product_discount_packages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_discount_package.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product_discount_package.description %>
</p>

<p>
  <strong>Discount percentage:</strong>
  <%= @product_discount_package.discount_percentage %>
</p>

<%= link_to 'Edit', edit_product_discount_package_path(@product_discount_package) %> |
<%= link_to 'Back', product_discount_packages_path %>