config/routes.rb
Rails.application.routes.draw do
  resources :contact_forms
  resources :product_discount_packages
  resources :products
  resources :product_types
  get 'main/home'
  get 'main/contact'
  root 'main#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  before_action :set_contact_form, only: %i[ show edit update destroy ]

  # GET /contact_forms or /contact_forms.json
  def index
    @contact_forms = ContactForm.all
  end

  # GET /contact_forms/1 or /contact_forms/1.json
  def show
  end

  # GET /contact_forms/new
  def new
    @contact_form = ContactForm.new
  end

  # GET /contact_forms/1/edit
  def edit
  end

  # POST /contact_forms or /contact_forms.json
  def create
    @contact_form = ContactForm.new(contact_form_params)

    respond_to do |format|
      if @contact_form.save
        format.html { redirect_to @contact_form, notice: "Contact form was successfully created." }
        format.json { render :show, status: :created, location: @contact_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_forms/1 or /contact_forms/1.json
  def update
    respond_to do |format|
      if @contact_form.update(contact_form_params)
        format.html { redirect_to @contact_form, notice: "Contact form was successfully updated." }
        format.json { render :show, status: :ok, location: @contact_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_forms/1 or /contact_forms/1.json
  def destroy
    @contact_form.destroy
    respond_to do |format|
      format.html { redirect_to contact_forms_url, notice: "Contact form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_form
      @contact_form = ContactForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_form_params
      params.require(:contact_form).permit(:first_name, :last_name, :phone_number, :email, :message)
    end
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/views/contact_forms/_form.html.erb
<%= form_with(model: contact_form) do |form| %>
  <% if contact_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact_form.errors.count, "error") %> prohibited this contact_form from being saved:</h2>

      <ul>
        <% contact_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contact_forms/edit.html.erb
<h1>Editing Contact Form</h1>

<%= render 'form', contact_form: @contact_form %>

<%= link_to 'Show', @contact_form %> |
<%= link_to 'Back', contact_forms_path %>

app/views/contact_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact Forms</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_forms.each do |contact_form| %>
      <tr>
        <td><%= contact_form.first_name %></td>
        <td><%= contact_form.last_name %></td>
        <td><%= contact_form.phone_number %></td>
        <td><%= contact_form.email %></td>
        <td><%= contact_form.message %></td>
        <td><%= link_to 'Show', contact_form %></td>
        <td><%= link_to 'Edit', edit_contact_form_path(contact_form) %></td>
        <td><%= link_to 'Destroy', contact_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Form', new_contact_form_path %>

app/views/contact_forms/new.html.erb
<h1>New Contact Form</h1>

<%= render 'form', contact_form: @contact_form %>

<%= link_to 'Back', contact_forms_path %>

app/views/contact_forms/show.html.erb
<p id="notice"><%= notice %></p>

<section class="collection section-b-space ratio_square " style="background-image: url('<%= image_path 'products-background.png'  %>')">
<p>
  <strong>First name:</strong>
  <%= @contact_form.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact_form.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @contact_form.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_form.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact_form.message %>
</p>

<%= link_to 'Edit', edit_contact_form_path(@contact_form) %> |
<%= link_to 'Back', contact_forms_path %>
</section> 